using System.Linq;
using System.Text;

namespace FlanderDev.RouteGen.Generators;

/// <summary>Emits the concrete <see cref="System.Net.Http.HttpClient"/>-backed client implementation for a parsed <see cref="ApiInterfaceModel"/>.</summary>
internal static class ClientImplementationEmitter
{
    /// <summary>Renders the full generated source (including <c>#nullable enable</c>, usings, and namespace) for <paramref name="model"/>'s client implementation.</summary>
    public static string Emit(ApiInterfaceModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// GENERATED by RouteGen from " + model.InterfaceName + " — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        string indent = hasNamespace ? "    " : "";
        string className = "Http" + model.ShortName + "Api";
        string fqInterface = string.IsNullOrEmpty(model.Namespace)
            ? "global::" + model.InterfaceName
            : "global::" + model.Namespace + "." + model.InterfaceName;

        sb.Append(indent).Append("public sealed class ").Append(className)
          .Append("(global::System.Net.Http.IHttpClientFactory factory) : ").AppendLine(fqInterface);
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    private readonly HttpClient _http = factory.CreateClient(\"")
          .Append(EscapeString(model.HttpClientName)).AppendLine("\");");
        sb.AppendLine();

        foreach (var method in model.Methods)
            EmitClientMethod(sb, indent + "    ", method, model.AbstractionsNamespace);

        sb.Append(indent).AppendLine("}");

        if (hasNamespace) sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>Emits one client method body: URL/query-string building (or multipart content building), the HTTP call, and response handling for <paramref name="method"/>.</summary>
    private static void EmitClientMethod(
        StringBuilder sb,
        string indent,
        ApiMethodModel method,
        string abstractionsNamespace)
    {
        string returnType = method.ResponseTypeFullName is null
            ? "global::System.Threading.Tasks.Task"
            : $"global::System.Threading.Tasks.Task<{method.ResponseTypeFullName}>";

        var paramList = string.Join(", ", method.Parameters.Select(FormatParameter));

        sb.Append(indent).Append("public async ").Append(returnType).Append(' ')
          .Append(method.Name).Append('(').Append(paramList).AppendLine(")");
        sb.Append(indent).AppendLine("{");

        string bodyIndent = indent + "    ";

        sb.Append(bodyIndent).Append("var __url = new StringBuilder(\"");
        sb.Append(BuildInterpolatedTemplateLiteral(method.RouteTemplate, method));
        sb.AppendLine("\");");

        var queryParams = method.Parameters.Where(p => p.Kind == ParameterKind.Query).ToList();
        if (queryParams.Count > 0)
        {
            sb.Append(bodyIndent).AppendLine(
                "var __query = new System.Collections.Generic.List<string>();");

            foreach (var q in queryParams)
            {
                if (q.IsNullable)
                {
                    sb.Append(bodyIndent).Append("if (").Append(q.Name).AppendLine(" is not null)");
                    sb.Append(bodyIndent).Append("    __query.Add($\"")
                      .Append(q.Name)
                      .Append("={Uri.EscapeDataString(")
                      .Append(q.Name)
                      .AppendLine("!.ToString()!)}\");");
                }
                else
                {
                    sb.Append(bodyIndent).Append("__query.Add($\"")
                      .Append(q.Name)
                      .Append("={Uri.EscapeDataString(")
                      .Append(q.Name)
                      .AppendLine(".ToString() ?? string.Empty)}\");");
                }
            }

            sb.Append(bodyIndent)
              .AppendLine("if (__query.Count > 0) __url.Append('?').Append(string.Join(\"&\", __query));");
        }

        var ctParam = method.Parameters.FirstOrDefault(
            p => p.Kind == ParameterKind.CancellationToken);

        string ctArg = ctParam is not null ? ctParam.Name : "CancellationToken.None";

        var bodyParam = method.Parameters.FirstOrDefault(
            p => p.Kind == ParameterKind.Body);

        string httpCall;

        if (method.UsesMultipart)
        {
            EmitMultipartContentBuilding(sb, bodyIndent, method);

            httpCall = method.Verb switch
            {
                "PUT" => $"_http.PutAsync(__url.ToString(), __content, {ctArg})",
                "PATCH" => $"_http.PatchAsync(__url.ToString(), __content, {ctArg})",
                // POST is by far the common case for uploads; also the fallback for GET/DELETE,
                // which aren't blocked from using [Form]/[File] but are unusual enough not to
                // warrant their own diagnostic the way [Body] on GET/DELETE gets one (RG0002).
                _ => $"_http.PostAsync(__url.ToString(), __content, {ctArg})"
            };
        }
        else
        {
            httpCall = method.Verb switch
        {
            "GET" => "_http.GetAsync(__url.ToString(), " + ctArg + ")",
            "DELETE" => "_http.DeleteAsync(__url.ToString(), " + ctArg + ")",
            "POST" => bodyParam is not null
                ? $"_http.PostAsJsonAsync(__url.ToString(), {bodyParam.Name}, {ctArg})"
                : $"_http.PostAsync(__url.ToString(), null, {ctArg})",
            "PUT" => bodyParam is not null
                ? $"_http.PutAsJsonAsync(__url.ToString(), {bodyParam.Name}, {ctArg})"
                : $"_http.PutAsync(__url.ToString(), null, {ctArg})",
            "PATCH" => bodyParam is not null
                ? $"_http.PatchAsJsonAsync(__url.ToString(), {bodyParam.Name}, {ctArg})"
                : $"_http.PatchAsync(__url.ToString(), null, {ctArg})",
            _ => "_http.GetAsync(__url.ToString(), " + ctArg + ")"
        };
        }

        sb.Append(bodyIndent).Append("var __response = await ").Append(httpCall).AppendLine(";");
        sb.Append(bodyIndent).AppendLine("if (!__response.IsSuccessStatusCode)");
        sb.Append(bodyIndent).AppendLine("{");
        sb.Append(bodyIndent).Append("    var __errorBody = await __response.Content.ReadAsStringAsync(")
          .Append(ctParam is not null ? ctArg : "").AppendLine(");");
        sb.Append(bodyIndent)
          .Append("    throw new global::")
          .Append(abstractionsNamespace)
          .AppendLine(".ApiException(__response.StatusCode, __errorBody);");
        sb.Append(bodyIndent).AppendLine("}");

        if (method.ResponseTypeFullName is null)
        {
            // Task, no response body expected.
        }
        else if (method.IsStreamResponse)
        {
            sb.Append(bodyIndent).Append("return await __response.Content.ReadAsStreamAsync(")
              .Append(ctParam is not null ? ctArg : "").AppendLine(");");
        }
        else
        {
            sb.Append(bodyIndent).Append("return (await __response.Content.ReadFromJsonAsync<")
              .Append(method.ResponseTypeFullName)
              .Append(">(cancellationToken: ")
              .Append(ctArg)
              .Append("))");
            sb.AppendLine(method.IsResponseNullable ? ";" : "!;");
        }

        sb.Append(indent).AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>Builds the <c>MultipartFormDataContent</c> and adds one part per <c>[Form]</c>/<c>[File]</c> parameter for a <see cref="ApiMethodModel.UsesMultipart"/> method.</summary>
    private static void EmitMultipartContentBuilding(StringBuilder sb, string bodyIndent, ApiMethodModel method)
    {
        sb.Append(bodyIndent).AppendLine("var __content = new MultipartFormDataContent();");

        foreach (var p in method.Parameters.Where(p => p.Kind == ParameterKind.Form))
        {
            // Simple types (the only kind [Form] used to allow) keep going through plain
            // ToString(); anything else is JSON-serialized into the field instead, since a
            // complex object has no meaningful single-string form otherwise. The server mirrors
            // this exact split -- see ServerControllerEmitter.FormatParameter.
            string valueExpr = p.IsSimpleType
                ? (p.IsNullable ? p.Name + "!.ToString()!" : p.Name + ".ToString() ?? string.Empty")
                : "System.Text.Json.JsonSerializer.Serialize(" + (p.IsNullable ? p.Name + "!" : p.Name) + ")";

            string contentExpr = p.IsSimpleType
                ? "new StringContent(" + valueExpr + ")"
                : "new StringContent(" + valueExpr + ", System.Text.Encoding.UTF8, \"application/json\")";

            if (p.IsNullable)
            {
                sb.Append(bodyIndent).Append("if (").Append(p.Name).AppendLine(" is not null)");
                sb.Append(bodyIndent).Append("    __content.Add(").Append(contentExpr)
                  .Append(", \"").Append(p.Name).AppendLine("\");");
            }
            else
            {
                sb.Append(bodyIndent).Append("__content.Add(").Append(contentExpr)
                  .Append(", \"").Append(p.Name).AppendLine("\");");
            }
        }

        foreach (var p in method.Parameters.Where(p => p.Kind == ParameterKind.File))
        {
            if (p.IsMultiFile)
                EmitMultiFilePart(sb, bodyIndent, p);
            else
                EmitSingleFilePart(sb, bodyIndent, p);
        }
    }

    /// <summary>Emits the <c>StreamContent</c> part for a single-file <c>[File]</c> parameter <paramref name="p"/>, guarded by a null check when nullable.</summary>
    private static void EmitSingleFilePart(StringBuilder sb, string bodyIndent, ApiParameterModel p)
    {
        string indent = bodyIndent;
        string nullBang = p.IsNullable ? "!" : "";

        if (p.IsNullable)
        {
            sb.Append(bodyIndent).Append("if (").Append(p.Name).AppendLine(" is not null)");
            sb.Append(bodyIndent).AppendLine("{");
            indent = bodyIndent + "    ";
        }

        string partVar = "__part_" + p.Name;
        sb.Append(indent).Append("var ").Append(partVar).Append(" = new StreamContent(")
          .Append(p.Name).Append(nullBang).AppendLine(".Content);");
        sb.Append(indent).Append("if (").Append(p.Name).Append(nullBang).AppendLine(".ContentType is not null)");
        sb.Append(indent).Append("    ").Append(partVar)
          .Append(".Headers.ContentType = new global::System.Net.Http.Headers.MediaTypeHeaderValue(")
          .Append(p.Name).Append(nullBang).AppendLine(".ContentType);");
        sb.Append(indent).Append("__content.Add(").Append(partVar).Append(", \"").Append(p.Name)
          .Append("\", ").Append(p.Name).Append(nullBang).AppendLine(".FileName);");

        if (p.IsNullable)
            sb.Append(bodyIndent).AppendLine("}");
    }

    /// <summary>Emits one <c>StreamContent</c> part per item for a multi-file <c>[File]</c> parameter <paramref name="p"/>, guarded by a null check when nullable.</summary>
    private static void EmitMultiFilePart(StringBuilder sb, string bodyIndent, ApiParameterModel p)
    {
        string indent = bodyIndent;

        if (p.IsNullable)
        {
            sb.Append(bodyIndent).Append("if (").Append(p.Name).AppendLine(" is not null)");
            sb.Append(bodyIndent).AppendLine("{");
            indent = bodyIndent + "    ";
        }

        string loopVar = "__file_" + p.Name;
        string partVar = "__part_" + p.Name;

        sb.Append(indent).Append("foreach (var ").Append(loopVar).Append(" in ").Append(p.Name).AppendLine(")");
        sb.Append(indent).AppendLine("{");
        string loopIndent = indent + "    ";
        sb.Append(loopIndent).Append("var ").Append(partVar).Append(" = new StreamContent(")
          .Append(loopVar).AppendLine(".Content);");
        sb.Append(loopIndent).Append("if (").Append(loopVar).AppendLine(".ContentType is not null)");
        sb.Append(loopIndent).Append("    ").Append(partVar)
          .Append(".Headers.ContentType = new global::System.Net.Http.Headers.MediaTypeHeaderValue(")
          .Append(loopVar).AppendLine(".ContentType);");
        sb.Append(loopIndent).Append("__content.Add(").Append(partVar).Append(", \"").Append(p.Name)
          .Append("\", ").Append(loopVar).AppendLine(".FileName);");
        sb.Append(indent).AppendLine("}");

        if (p.IsNullable)
            sb.Append(bodyIndent).AppendLine("}");
    }

    /// <summary>Builds the C# string-literal expression for a method's request URL: literal text passed through as-is, route-token parts substituted with their matching (URL-escaped) parameter.</summary>
    private static string BuildInterpolatedTemplateLiteral(
        RouteTemplate template,
        ApiMethodModel method)
    {
        var sb = new StringBuilder();

        foreach (var part in template.Parts)
        {
            if (part is RouteLiteralPart literal)
            {
                foreach (char c in literal.Text)
                {
                    if (c == '"' || c == '\\')
                        sb.Append('\\');

                    sb.Append(c);
                }

                continue;
            }

            var parameter = (RouteParameterPart)part;
            var param = method.Parameters.FirstOrDefault(p =>
                p.MatchesRouteToken &&
                string.Equals(
                    p.RouteTokenNameOverride ?? p.Name,
                    parameter.Name,
                    System.StringComparison.OrdinalIgnoreCase));

            if (param is not null)
            {
                string accessor = param.IsNullable
                    ? param.Name + "?.ToString() ?? string.Empty"
                    : param.Name + ".ToString() ?? string.Empty";

                sb.Append("\" + Uri.EscapeDataString(")
                  .Append(accessor)
                  .Append(") + \"");
            }
            else
            {
                // This should normally have produced a diagnostic in ApiInterfaceReader.
                // Preserve the original token so source generation remains non-throwing.
                sb.Append('{').Append(parameter.Name);

                if (!string.IsNullOrEmpty(parameter.Constraint))
                    sb.Append(':').Append(parameter.Constraint);

                if (!string.IsNullOrEmpty(parameter.DefaultValue))
                    sb.Append('=').Append(parameter.DefaultValue);

                if (parameter.Optional)
                    sb.Append('?');

                sb.Append('}');
            }
        }

        return sb.ToString();
    }

    /// <summary>Formats one client method parameter, including its default value when the interface declared one.</summary>
    private static string FormatParameter(ApiParameterModel p)
    {
        if (p.Kind == ParameterKind.CancellationToken)
            return "CancellationToken " + p.Name + " = default";

        string result = p.TypeFullName + " " + p.Name;

        if (p.HasDefaultValue)
            result += " = " + p.DefaultValueLiteral;

        return result;
    }

    /// <summary>Escapes backslashes and double quotes for embedding <paramref name="s"/> in a generated C# string literal.</summary>
    private static string EscapeString(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
