using System.Linq;
using System.Text;

namespace FlanderDev.RouteGen.Generators;

/// <summary>Emits the abstract MVC controller base class for a parsed <see cref="ApiInterfaceModel"/>.</summary>
internal static class ServerControllerEmitter
{
    /// <summary>Renders the full generated source (including <c>#nullable enable</c>, usings, and namespace) for <paramref name="model"/>'s abstract controller base.</summary>
    public static string Emit(ApiInterfaceModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// GENERATED by RouteGen from " + model.InterfaceName + " — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc.ModelBinding;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        const string indent = ""; // file-scoped namespace: no extra nesting level needed
        string className = model.ShortName + "ApiControllerBase";

        sb.Append(indent).Append('[').Append("Route(\"").Append(EscapeString(model.BaseRoute)).Append("\")]").AppendLine();
        sb.Append(indent).AppendLine("[ApiController]");
        if (model.InterfaceLevelAuthorize)
            sb.Append(indent).AppendLine(FormatAuthorizeAttribute(model.InterfaceLevelRoles, model.InterfaceLevelPolicy));
        sb.Append(indent).Append("public abstract class ").Append(className).AppendLine(" : ControllerBase");
        sb.Append(indent).AppendLine("{");

        bool needsFileWithData = model.Methods.Any(m =>
            m.Parameters.Any(p => p.Kind == ParameterKind.File && p.IsFileWithData));

        bool needsJsonFormBinder = model.Methods.Any(m =>
            m.Parameters.Any(p => p.Kind == ParameterKind.Form && !p.IsSimpleType));

        if (needsFileWithData)
            EmitFileWithDataSupport(sb, indent + "    ");

        if (needsJsonFormBinder)
            EmitJsonFormFieldBinder(sb, indent + "    ");

        foreach (var method in model.Methods)
        {
            EmitControllerMethod(sb, indent + "    ", method);
        }

        sb.Append(indent).AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the nested <c>FileWithData&lt;TData&gt;</c> record plus the two generic
    /// <see cref="IModelBinder"/>s (single and list) that reconstruct it from a file part and a
    /// JSON-serialized data part correlated by field name, <c>{name}.file</c>/<c>{name}.data</c>
    /// for a single parameter, <c>{name}[0].file</c>/<c>{name}[0].data</c> (and so on) for a
    /// list. Nested inside the controller base (rather than a shared external type) so multiple
    /// generated controllers never collide on the name, and generic over <c>TData</c> so one
    /// definition serves every <c>[File] FileWithData&lt;T&gt;</c> parameter in this interface
    /// regardless of what <c>T</c> each one closes over.
    /// </summary>
    private static void EmitFileWithDataSupport(StringBuilder sb, string indent)
    {
        sb.Append(indent).AppendLine("public sealed record FileWithData<TData>(IFormFile File, TData Data);");
        sb.AppendLine();

        sb.Append(indent).AppendLine("private sealed class FileWithDataBinder<TData> : IModelBinder");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    public System.Threading.Tasks.Task BindModelAsync(ModelBindingContext bindingContext)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        string fieldName = bindingContext.FieldName;");
        sb.Append(indent).AppendLine("        var file = bindingContext.HttpContext.Request.Form.Files.GetFile(fieldName + \".file\");");
        sb.Append(indent).AppendLine("        bool hasData = bindingContext.HttpContext.Request.Form.TryGetValue(fieldName + \".data\", out var dataValues);");
        sb.AppendLine();
        sb.Append(indent).AppendLine("        if (file is null || !hasData)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            bindingContext.Result = ModelBindingResult.Success(null);");
        sb.Append(indent).AppendLine("            return System.Threading.Tasks.Task.CompletedTask;");
        sb.Append(indent).AppendLine("        }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("        try");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            var data = System.Text.Json.JsonSerializer.Deserialize<TData>(dataValues.ToString())!;");
        sb.Append(indent).AppendLine("            bindingContext.Result = ModelBindingResult.Success(new FileWithData<TData>(file, data));");
        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine("        catch (System.Text.Json.JsonException ex)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            bindingContext.ModelState.TryAddModelError(bindingContext.ModelName, $\"Invalid JSON for '{fieldName}.data': {ex.Message}\");");
        sb.Append(indent).AppendLine("            bindingContext.Result = ModelBindingResult.Failed();");
        sb.Append(indent).AppendLine("        }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("        return System.Threading.Tasks.Task.CompletedTask;");
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");
        sb.AppendLine();

        sb.Append(indent).AppendLine("private sealed class FileWithDataListBinder<TData> : IModelBinder");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    public System.Threading.Tasks.Task BindModelAsync(ModelBindingContext bindingContext)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        string fieldName = bindingContext.FieldName;");
        sb.Append(indent).AppendLine("        var form = bindingContext.HttpContext.Request.Form;");
        sb.Append(indent).AppendLine("        var result = new System.Collections.Generic.List<FileWithData<TData>>();");
        sb.AppendLine();
        sb.Append(indent).AppendLine("        for (int i = 0; ; i++)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            string prefix = $\"{fieldName}[{i}]\";");
        sb.Append(indent).AppendLine("            var file = form.Files.GetFile(prefix + \".file\");");
        sb.Append(indent).AppendLine("            bool hasData = form.TryGetValue(prefix + \".data\", out var dataValues);");
        sb.AppendLine();
        sb.Append(indent).AppendLine("            if (file is null && !hasData)");
        sb.Append(indent).AppendLine("                break;");
        sb.AppendLine();
        sb.Append(indent).AppendLine("            if (file is null || !hasData)");
        sb.Append(indent).AppendLine("            {");
        sb.Append(indent).AppendLine("                bindingContext.ModelState.TryAddModelError(bindingContext.ModelName, $\"'{prefix}' is missing its file or data part.\");");
        sb.Append(indent).AppendLine("                bindingContext.Result = ModelBindingResult.Failed();");
        sb.Append(indent).AppendLine("                return System.Threading.Tasks.Task.CompletedTask;");
        sb.Append(indent).AppendLine("            }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("            try");
        sb.Append(indent).AppendLine("            {");
        sb.Append(indent).AppendLine("                var data = System.Text.Json.JsonSerializer.Deserialize<TData>(dataValues.ToString())!;");
        sb.Append(indent).AppendLine("                result.Add(new FileWithData<TData>(file, data));");
        sb.Append(indent).AppendLine("            }");
        sb.Append(indent).AppendLine("            catch (System.Text.Json.JsonException ex)");
        sb.Append(indent).AppendLine("            {");
        sb.Append(indent).AppendLine("                bindingContext.ModelState.TryAddModelError(bindingContext.ModelName, $\"Invalid JSON for '{prefix}.data': {ex.Message}\");");
        sb.Append(indent).AppendLine("                bindingContext.Result = ModelBindingResult.Failed();");
        sb.Append(indent).AppendLine("                return System.Threading.Tasks.Task.CompletedTask;");
        sb.Append(indent).AppendLine("            }");
        sb.Append(indent).AppendLine("        }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("        bindingContext.Result = ModelBindingResult.Success(result);");
        sb.Append(indent).AppendLine("        return System.Threading.Tasks.Task.CompletedTask;");
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits a nested <see cref="IModelBinder"/> that reads a raw <c>multipart/form-data</c>
    /// field and JSON-deserializes it into the target parameter type. Used for <c>[Form]</c>
    /// parameters whose type isn't simple (<see cref="ApiParameterModel.IsSimpleType"/> false),
    /// which, unlike a plain <c>[FromForm]</c> simple-type field, have no meaningful
    /// per-property multipart binding without one. Nested inside the controller base (rather
    /// than a single shared type) purely so multiple generated controllers never collide on the
    /// name; reads directly from <c>Request.Form</c> rather than the composite value provider so
    /// it can never accidentally bind from the route or query string instead.
    /// </summary>
    private static void EmitJsonFormFieldBinder(StringBuilder sb, string indent)
    {
        sb.Append(indent).AppendLine("private sealed class JsonFormFieldBinder : IModelBinder");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    public System.Threading.Tasks.Task BindModelAsync(ModelBindingContext bindingContext)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        var valueProviderResult = bindingContext.HttpContext.Request.Form.TryGetValue(bindingContext.FieldName, out var values) ? values : Microsoft.Extensions.Primitives.StringValues.Empty;");
        sb.Append(indent).AppendLine("        string? raw = valueProviderResult.Count > 0 ? valueProviderResult.ToString() : null;");
        sb.AppendLine();
        sb.Append(indent).AppendLine("        if (string.IsNullOrEmpty(raw))");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            bindingContext.Result = ModelBindingResult.Success(null);");
        sb.Append(indent).AppendLine("            return System.Threading.Tasks.Task.CompletedTask;");
        sb.Append(indent).AppendLine("        }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("        try");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            var model = System.Text.Json.JsonSerializer.Deserialize(raw, bindingContext.ModelType);");
        sb.Append(indent).AppendLine("            bindingContext.Result = ModelBindingResult.Success(model);");
        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine("        catch (System.Text.Json.JsonException ex)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            bindingContext.ModelState.TryAddModelError(bindingContext.ModelName, $\"Invalid JSON for form field '{bindingContext.FieldName}': {ex.Message}\");");
        sb.Append(indent).AppendLine("            bindingContext.Result = ModelBindingResult.Failed();");
        sb.Append(indent).AppendLine("        }");
        sb.AppendLine();
        sb.Append(indent).AppendLine("        return System.Threading.Tasks.Task.CompletedTask;");
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>Emits one abstract action method (verb/route/authorization attributes plus the signature) for <paramref name="method"/>.</summary>
    private static void EmitControllerMethod(StringBuilder sb, string indent, ApiMethodModel method)
    {
        string httpAttr = method.Verb switch
        {
            "GET" => "HttpGet",
            "POST" => "HttpPost",
            "PUT" => "HttpPut",
            "DELETE" => "HttpDelete",
            "PATCH" => "HttpPatch",
            _ => "HttpGet"
        };

        sb.Append(indent).Append('[').Append(httpAttr);
        if (!string.IsNullOrEmpty(method.RouteSuffix))
            sb.Append("(\"").Append(EscapeString(method.RouteSuffix!)).Append("\")");
        sb.AppendLine("]");

        if (method.AllowAnonymous)
        {
            sb.Append(indent).AppendLine("[AllowAnonymous]");
        }
        else if (method.HasAuthorize)
        {
            sb.Append(indent).AppendLine(FormatAuthorizeAttribute(method.Roles, method.Policy));
        }

        string returnType = ActionResultReturnType(method);
        sb.Append(indent).Append("public abstract ").Append(returnType).Append(' ').Append(method.Name).Append('(');

        var paramStrings = method.Parameters.Select(FormatParameter).ToList();
        sb.Append(string.Join(", ", paramStrings));
        sb.AppendLine(");");
        sb.AppendLine();
    }

    /// <summary>Computes the generated action method's <c>Task&lt;ActionResult&lt;...&gt;&gt;</c>-shaped return type for <paramref name="method"/>.</summary>
    private static string ActionResultReturnType(ApiMethodModel method)
    {
        if (method.ResponseTypeFullName is null)
            return "global::System.Threading.Tasks.Task<IActionResult>";

        if (method.IsStreamResponse)
            return "global::System.Threading.Tasks.Task<ActionResult>";

        return $"global::System.Threading.Tasks.Task<ActionResult<{method.ResponseTypeFullName}>>";
    }

    /// <summary>Formats one method parameter, including its ASP.NET Core binding attribute (<c>[FromRoute]</c>/<c>[FromQuery]</c>/<c>[FromBody]</c>/<c>[FromForm]</c>/<c>[ModelBinder]</c>) and default value.</summary>
    private static string FormatParameter(ApiParameterModel p)
    {
        if (p.Kind == ParameterKind.CancellationToken)
        {
            // AssignCancellationTokenDefault (in ApiInterfaceReader) already decided whether this
            // can safely get a default without pushing a later required parameter into an
            // invalid "required after optional" position (CS1737), respect that decision
            // exactly, the same as every other parameter kind, instead of forcing one here.
            string ctDefault = p.HasDefaultValue ? " = " + p.DefaultValueLiteral : "";
            return "global::System.Threading.CancellationToken " + p.Name + ctDefault;
        }

        if (p.Kind == ParameterKind.File)
        {
            // The client-side FormFile/FileWithData<TData> are wire-level convenience types;
            // ASP.NET Core's own model binder understands IFormFile, not FormFile, so this
            // deliberately ignores TypeFullName (which still says "FormFile"/"FileWithData<T>")
            // for this Kind. ServerFileTypeFullName was computed at parse time to mirror the
            // client's exact shape (array/List<>/IEnumerable<>/etc., FormFile or FileWithData<T>)
            // wherever ASP.NET Core's model binder (or RouteGen's own generated one, for
            // FileWithData<T>) is verified to support it, see TryGetFileParameterShape.
            string fileType = p.ServerFileTypeFullName!;

            if (p.IsNullable) fileType += "?";

            string fileDefault = p.IsNullable ? " = null" : "";

            // A plain FormFile/collection binds via ordinary [FromForm]. A FileWithData<TData>
            // has no natural multipart shape ASP.NET Core understands on its own, so it's bound
            // by the generated FileWithDataBinder<TData>/FileWithDataListBinder<TData> instead --
            // [ModelBinder] and [FromForm] can't be combined on the same parameter.
            string bindingAttr = p.IsFileWithData
                ? $"[ModelBinder(BinderType = typeof({(p.IsMultiFile ? "FileWithDataListBinder" : "FileWithDataBinder")}<{p.FileWithDataTypeFullName}>))] "
                : "[FromForm] ";

            return $"{bindingAttr}{fileType} {p.Name}{fileDefault}";
        }

        string binding = p.Kind switch
        {
            ParameterKind.Body => "[FromBody] ",
            ParameterKind.Query => "[FromQuery] ",
            // A simple-typed [Form] field binds via the ordinary [FromForm] path, unchanged.
            // A complex one has no meaningful per-property multipart shape, so it's JSON inside
            // one field instead, bound via the nested JsonFormFieldBinder emitted above rather
            // than [FromForm], since ModelBinderAttribute and FromFormAttribute can't be combined
            // on the same parameter.
            ParameterKind.Form => p.IsSimpleType
                ? "[FromForm] "
                : "[ModelBinder(BinderType = typeof(JsonFormFieldBinder))] ",
            ParameterKind.RouteOrAuto => "[FromRoute] ",
            _ => ""
        };

        string result = binding + p.TypeFullName + " " + p.Name;
        if (p.HasDefaultValue)
            result += " = " + p.DefaultValueLiteral;
        return result;
    }

    /// <summary>Formats an <c>[Authorize]</c>/<c>[Authorize(Roles = ..., Policy = ...)]</c> attribute from the given roles/policy.</summary>
    private static string FormatAuthorizeAttribute(string? roles, string? policy)
    {
        var args = new System.Collections.Generic.List<string>();
        if (!string.IsNullOrEmpty(roles)) args.Add($"Roles = \"{EscapeString(roles!)}\"");
        if (!string.IsNullOrEmpty(policy)) args.Add($"Policy = \"{EscapeString(policy!)}\"");
        return args.Count == 0 ? "[Authorize]" : $"[Authorize({string.Join(", ", args)})]";
    }

    /// <summary>Escapes backslashes and double quotes for embedding <paramref name="s"/> in a generated C# string literal.</summary>
    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
