using System.Linq;
using System.Text;

namespace FlanderDev.RouteGen.Generators;

internal static class ServerControllerEmitter
{
    public static string Emit(ApiInterfaceModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// GENERATED by RouteGen from " + model.InterfaceName + " — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        string indent = hasNamespace ? "    " : "";
        string className = model.ShortName + "ApiControllerBase";

        sb.Append(indent).Append('[').Append("Route(\"").Append(EscapeString(model.BaseRoute)).Append("\")]").AppendLine();
        sb.Append(indent).AppendLine("[ApiController]");
        if (model.InterfaceLevelAuthorize)
            sb.Append(indent).AppendLine(FormatAuthorizeAttribute(model.InterfaceLevelRoles, model.InterfaceLevelPolicy));
        sb.Append(indent).Append("public abstract class ").Append(className).AppendLine(" : ControllerBase");
        sb.Append(indent).AppendLine("{");

        foreach (var method in model.Methods)
        {
            EmitControllerMethod(sb, indent + "    ", method);
        }

        sb.Append(indent).AppendLine("}");

        if (hasNamespace) sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitControllerMethod(StringBuilder sb, string indent, ApiMethodModel method)
    {
        string httpAttr = method.Verb switch
        {
            "GET" => "HttpGet",
            "POST" => "HttpPost",
            "PUT" => "HttpPut",
            "DELETE" => "HttpDelete",
            "PATCH" => "HttpPatch",
            _ => "HttpGet"
        };

        sb.Append(indent).Append('[').Append(httpAttr);
        if (!string.IsNullOrEmpty(method.RouteSuffix))
            sb.Append("(\"").Append(EscapeString(method.RouteSuffix!)).Append("\")");
        sb.AppendLine("]");

        if (method.AllowAnonymous)
        {
            sb.Append(indent).AppendLine("[AllowAnonymous]");
        }
        else if (method.HasAuthorize)
        {
            sb.Append(indent).AppendLine(FormatAuthorizeAttribute(method.Roles, method.Policy));
        }

        string returnType = ActionResultReturnType(method);
        sb.Append(indent).Append("public abstract ").Append(returnType).Append(' ').Append(method.Name).Append('(');

        var paramStrings = method.Parameters.Select(FormatParameter).ToList();
        sb.Append(string.Join(", ", paramStrings));
        sb.AppendLine(");");
        sb.AppendLine();
    }

    private static string ActionResultReturnType(ApiMethodModel method)
    {
        if (method.ResponseTypeFullName is null)
            return "global::System.Threading.Tasks.Task<IActionResult>";

        if (method.IsStreamResponse)
            return "global::System.Threading.Tasks.Task<ActionResult>";

        return $"global::System.Threading.Tasks.Task<ActionResult<{method.ResponseTypeFullName}>>";
    }

    private static string FormatParameter(ApiParameterModel p)
    {
        if (p.Kind == ParameterKind.CancellationToken)
            return "global::System.Threading.CancellationToken " + p.Name + " = default";

        string binding = p.Kind switch
        {
            ParameterKind.Body => "[FromBody] ",
            ParameterKind.Query => "[FromQuery] ",
            ParameterKind.RouteOrAuto => "[FromRoute] ",
            _ => ""
        };

        string result = binding + p.TypeFullName + " " + p.Name;
        if (p.HasDefaultValue)
            result += " = " + p.DefaultValueLiteral;
        return result;
    }

    private static string FormatAuthorizeAttribute(string? roles, string? policy)
    {
        var args = new System.Collections.Generic.List<string>();
        if (!string.IsNullOrEmpty(roles)) args.Add($"Roles = \"{EscapeString(roles!)}\"");
        if (!string.IsNullOrEmpty(policy)) args.Add($"Policy = \"{EscapeString(policy!)}\"");
        return args.Count == 0 ? "[Authorize]" : $"[Authorize({string.Join(", ", args)})]";
    }

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
