using System;
using System.Linq;
using System.Text;

namespace FlanderDev.RouteGen.Migration;

/// <summary>
/// Renders the full source text of the one-time, editable interface file generated from a
/// <see cref="ControllerMigrationModel"/>. Unlike RouteGen.Generators' emitters, this output is
/// meant to be reviewed and committed as ordinary source, not regenerated on every build -- see
/// the banner comment this emits, which is deliberately distinct from the "// GENERATED by
/// RouteGen ... do not edit" banner the forward generators use, so the two are never confused.
/// </summary>
internal static class MigratedInterfaceEmitter
{
    /// <summary>Renders the full generated file for <paramref name="model"/>.</summary>
    public static string Emit(ControllerMigrationModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated ONCE by RouteGen.Migration from " + model.ControllerName +
            " on " + DateTime.Now.ToString("yyyy-MM-dd") + ".");
        sb.AppendLine("// This is a normal, EDITABLE source file -- it will not be regenerated. Review it, then:");
        sb.AppendLine("//   1. Move this file to your Shared project if it didn't land there automatically.");
        sb.AppendLine("//   2. Address every TODO below (skipped actions, dropped attributes, types that need to move too).");
        sb.AppendLine("//   3. Point " + model.ControllerName + " at the generated " +
            ControllerMigrationReader.StemFromControllerName(model.ControllerName) +
            "ApiControllerBase and remove its own [Route]/[Http*] attributes.");
        sb.AppendLine("// See the RouteGen.Migration README for the full walkthrough.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using FlanderDev.RouteGen.Abstractions;");
        sb.AppendLine();

        if (model.SkippedActionNotes.Count > 0)
        {
            sb.AppendLine("// TODO: the following actions were NOT migrated and need to be added by hand (or kept");
            sb.AppendLine("// as separate hand-written actions on the concrete controller after migration):");
            foreach (var note in model.SkippedActionNotes)
                sb.Append("//   - ").AppendLine(note);
            sb.AppendLine();
        }

        if (model.LocalTypeNames.Count > 0)
        {
            sb.AppendLine("// TODO: these types are currently declared in the Server project. Moving this interface");
            sb.AppendLine("// to Shared will not compile until they move too (or Shared references wherever they end up):");
            foreach (var typeName in model.LocalTypeNames)
                sb.Append("//   - ").AppendLine(typeName);
            sb.AppendLine();
        }

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").AppendLine(model.Namespace);
            sb.AppendLine("{");
        }

        string indent = hasNamespace ? "    " : "";

        sb.Append(indent).Append("[ApiRoute(\"").Append(EscapeString(model.BaseRoute)).AppendLine("\")]");
        sb.Append(indent).Append("public partial interface ").AppendLine(model.InterfaceName);
        sb.Append(indent).AppendLine("{");

        foreach (var action in model.Actions)
        {
            EmitAction(sb, indent + "    ", action);
        }

        sb.Append(indent).AppendLine("}");

        if (hasNamespace) sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitAction(StringBuilder sb, string indent, ActionMigrationModel action)
    {
        foreach (var note in action.DroppedAttributeNotes)
            sb.Append(indent).Append("// TODO: ").AppendLine(note);

        string verbAttr = "[" + action.Verb + (string.IsNullOrEmpty(action.RouteSuffix)
            ? "]"
            : "(\"" + EscapeString(action.RouteSuffix!) + "\")]");
        sb.Append(indent).AppendLine(verbAttr);

        if (action.AllowAnonymous)
        {
            sb.Append(indent).AppendLine("[AllowAnonymous]");
        }
        else if (action.HasAuthorize)
        {
            sb.Append(indent).AppendLine(FormatAuthorizeAttribute(action.Roles, action.Policy));
        }

        string returnType = action.ResponseTypeFullName is null
            ? "Task"
            : $"Task<{action.ResponseTypeFullName}>";

        string paramList = string.Join(", ", action.Parameters.Select(FormatParameter));

        sb.Append(indent).Append(returnType).Append(' ').Append(action.Name)
          .Append('(').Append(paramList).AppendLine(");");
        sb.AppendLine();
    }

    private static string FormatParameter(ActionParameterMigrationModel p)
    {
        string binding = p.Kind switch
        {
            MigratedParameterKind.Query => "[Query] ",
            MigratedParameterKind.Body => "[Body] ",
            MigratedParameterKind.Form => "[Form] ",
            MigratedParameterKind.File => "[File] ",
            _ => "" // Route: no attribute needed, RouteGen infers it from the route template.
        };

        return binding + p.TypeFullName + " " + p.Name;
    }

    private static string FormatAuthorizeAttribute(string? roles, string? policy)
    {
        var args = new System.Collections.Generic.List<string>();
        if (!string.IsNullOrEmpty(roles)) args.Add($"Roles = \"{EscapeString(roles!)}\"");
        if (!string.IsNullOrEmpty(policy)) args.Add($"Policy = \"{EscapeString(policy!)}\"");
        return args.Count == 0 ? "[Authorize]" : $"[Authorize({string.Join(", ", args)})]";
    }

    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
